// Synthetic data generator: catalog -> conjunction screen of the demo operator's fleet -> fixtures with provenance and quality checks.
// Run: node data/simulators/generate.ts   (writes data/fixtures/*.json; deterministic for a given seed)
import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { generateCatalog, parse, screen, toConjunction, checksum, stateAt, matchEncounters, type Encounter } from "../../packages/domain/src/index.ts";
import { wasmBatch } from "../../packages/domain/src/wasm.ts";

const out = new URL("../fixtures/", import.meta.url);
mkdirSync(out, { recursive: true });
const seed = Number(process.env.SEED ?? 20261006);
const t0 = Date.now();
const cat = generateCatalog(seed);
const epoch = new Date(cat.epoch);
const sats = cat.objects.map((o) => parse(o.l1, o.l2));
const fleet = cat.objects.map((o, i) => (o.operator === "aurora" ? i : -1)).filter((i) => i >= 0);
const batch = await wasmBatch();
const { encounters, stats } = screen({ sats, primaries: fleet, start: epoch, hours: 24, batch });
const conj = encounters.map((e, i) => toConjunction(e, cat.objects, sats, epoch, i));

// quality checks, recorded with the data
const checks = {
  objects: cat.objects.length,
  tleChecksumsValid: cat.objects.every((o) => +o.l1[68] === checksum(o.l1) && +o.l2[68] === checksum(o.l2)),
  propagatesAtEpoch: cat.objects.filter((o, i) => stateAt(sats[i], epoch) !== null).length,
  uniqueNorad: new Set(cat.objects.map((o) => o.norad)).size === cat.objects.length,
  plantedFound: cat.planted.map((p) => {
    const hit = conj.filter((c) => c.primaryNorad === p.primary && c.secondaryNorad === p.secondary)
      .sort((a, b) => Math.abs(Date.parse(a.tca) - Date.parse(p.tca)) - Math.abs(Date.parse(b.tca) - Date.parse(p.tca)))[0];
    return { ...p, foundMissM: hit?.missM ?? null, foundTcaOffsetS: hit ? (Date.parse(hit.tca) - Date.parse(p.tca)) / 1000 : null, pc: hit?.pc ?? null };
  }),
  conjunctions: conj.length,
  byRisk: { high: conj.filter((c) => c.risk === "high").length, medium: conj.filter((c) => c.risk === "medium").length, low: conj.filter((c) => c.risk === "low").length },
  screenStats: { ...stats, ms: Math.round(stats.ms) },
};
if (!checks.tleChecksumsValid || !checks.uniqueNorad || checks.propagatesAtEpoch !== checks.objects || checks.plantedFound.some((p) => p.foundMissM === null))
  throw new Error("quality checks failed: " + JSON.stringify(checks, null, 1));

// compact catalog for the browser: one array per object
const opIdx = new Map(cat.operators.map((o, i) => [o.slug, i]));
const compact = {
  version: cat.version, seed, epoch: cat.epoch, operators: cat.operators, planted: cat.planted,
  fields: ["norad", "name", "type", "operator", "family", "radiusM", "massKg", "sigmaR", "sigmaI", "sigmaC", "l1", "l2"],
  objects: cat.objects.map((o) => [o.norad, o.name, o.type, o.operator === null ? -1 : opIdx.get(o.operator), o.family, o.radiusM, o.massKg, ...o.sigmaM, o.l1, o.l2]),
};
const round = (x: number) => +x.toPrecision(9);
const conjOut = conj.map((c) => ({ ...c, covKm2: c.covKm2.map((r) => r.map((x) => +x.toPrecision(6))), rPrimary: c.rPrimary.map(round), vPrimary: c.vPrimary.map(round), rSecondary: c.rSecondary.map(round), vSecondary: c.vSecondary.map(round) }));
const files: Record<string, unknown> = { "catalog.json": compact, "conjunctions.json": { epoch: cat.epoch, screenedHours: 24, thresholdKm: 5, conjunctions: conjOut } };
const sha: Record<string, string> = {};
for (const [name, body] of Object.entries(files)) {
  const s = JSON.stringify(body);
  writeFileSync(new URL(name, out), s);
  sha[name] = createHash("sha256").update(s).digest("hex");
}
writeFileSync(new URL("provenance.json", out), JSON.stringify({
  datasets: [
    { name: "space-object catalog", provider: "synthetic: packages/domain/src/catalog.ts", license: "MIT (generated by this repository)", seed, epoch: cat.epoch, transformationVersion: cat.version, sha256: sha["catalog.json"] },
    { name: "conjunction screen (Aurora fleet, 24 h, 5 km)", provider: "synthetic: screen.ts over the catalog above", license: "MIT", transformationVersion: "screen-v1", sha256: sha["conjunctions.json"] },
    { name: "SGP4 verification vectors", provider: "Vallado, Crawford, Hujsak and Kelso, AIAA 2006-6753 (celestrak.org/publications/AIAA/2006-6753)", license: "published with the paper for verification use", file: "data/fixtures/sgp4-ver/" },
  ],
  qualityChecks: checks,
  generatedInMs: Date.now() - t0,
}, null, 1));
batch.dispose();
console.log(JSON.stringify({ objects: checks.objects, conjunctions: checks.conjunctions, byRisk: checks.byRisk, planted: checks.plantedFound.map((p) => [p.label, p.foundMissM, p.pc]), ms: Date.now() - t0 }));
// keep the evaluation helper reachable for scripts that import this module
export type { Encounter };
export { matchEncounters };
