"use client";
// The operations surface: conjunction list, inspector, time scrubber, feed status and notifications.
import { useEffect, useMemo, useState } from "react";
import { relTime, type Conjunction } from "@orbital/domain";
import { get, jump, loadCatalog, openConjunction, planAvoidance, provider, select, send, set, setStress, useApp, type Obj } from "../store.ts";
import { playEncounter, encounterClock } from "../scene/encounterClock.ts";
import { cms, hhmm, metres, n, pc, riskIcon, riskText, utc } from "./fmt.ts";

const name = (norad: number) => get().byNorad.get(norad)?.name ?? String(norad);

export function TopBar() {
  const s = { list: useApp((x) => x.listView), reduced: useApp((x) => x.reduced), paused: useApp((x) => x.motionPaused), hud: useApp((x) => x.hud), stress: useApp((x) => x.stress) };
  const [ops, setOps] = useState(false);
  return (
    <header className="topbar">
      <div className="brand"><b>ORBITAL</b><span className="badge" title="Every object, operator and conjunction is generated by this repository">SYNTHETIC DATA</span></div>
      <FeedPill />
      <nav aria-label="View controls">
        <button onClick={() => set({ palette: true })} aria-keyshortcuts="Control+K Meta+K">Search <kbd>⌘K</kbd></button>
        <button aria-pressed={s.list} onClick={() => set({ listView: !s.list })} aria-keyshortcuts="L">List view</button>
        <button aria-pressed={s.reduced} onClick={() => set({ reduced: !s.reduced })} aria-keyshortcuts="M">Reduced motion</button>
        <button aria-pressed={s.paused} onClick={() => set({ motionPaused: !s.paused, playing: false })} title="Pause all motion">{s.paused ? "Resume motion" : "Pause motion"}</button>
        <button aria-pressed={s.hud} onClick={() => set({ hud: !s.hud })}>Telemetry</button>
        <button onClick={() => set({ help: true })} aria-keyshortcuts="?">Keys</button>
        <div className="menu">
          <button aria-expanded={ops} onClick={() => setOps(!ops)}>Failure lab ▾</button>
          {ops ? (
            <div className="menu-pop" role="menu">
              <button role="menuitem" onClick={() => { setOps(false); provider.feedDown = true; set((x) => ({ feed: { ...x.feed, status: "down", message: "simulated outage" } })); loadCatalog(); }}>Cut the element-set feed</button>
              <button role="menuitem" onClick={() => { setOps(false); provider.feedDown = false; set((x) => ({ feed: { ...x.feed, message: "feed restored, waiting for next retry" } })); }}>Restore the feed</button>
              <button role="menuitem" onClick={() => { setOps(false); const c = document.querySelector<HTMLCanvasElement>(".globe canvas"); c?.getContext("webgl2")?.getExtension("WEBGL_lose_context")?.loseContext(); }}>Lose the GPU context</button>
              <button role="menuitem" aria-checked={s.stress} onClick={() => { setOps(false); setStress(!s.stress); }}>{s.stress ? "Back to 18,050 objects" : "Stress test: 50,000 objects"}</button>
            </div>
          ) : null}
        </div>
      </nav>
    </header>
  );
}

function FeedPill() {
  const f = useApp((s) => s.feed);
  const lastGood = f.lastGood ? Math.round((Date.now() - f.lastGood) / 60000) : null;
  const text = f.status === "ok" ? "Feed live" : f.status === "recovered" ? "Feed recovered" : f.status === "retrying" ? `Feed down · retry ${f.attempt} in ${Math.round(f.waitMs / 1000)} s` : "Feed down";
  return <span className={`pill feed-${f.status}`} role="status">{f.status === "ok" || f.status === "recovered" ? "●" : "▲"} {text}{f.status !== "ok" && lastGood !== null ? ` · last good ${lastGood} min ago` : ""}</span>;
}

export function Banner() {
  const f = useApp((s) => s.feed);
  if (f.status === "ok") return null;
  if (f.status === "recovered")
    return <div className="banner ok" role="status">Feed recovered: element sets refreshed and conjunctions re-read. <button onClick={() => set((s) => ({ feed: { ...s.feed, status: "ok" } }))}>Dismiss</button></div>;
  return (
    <div className="banner warn" role="alert">
      <b>Element-set feed unavailable</b> ({f.message}). Showing the last good catalog; uncertainty grows with element age, so treat Pc values as stale.
      {f.status === "retrying" ? <> Retrying with backoff (attempt {f.attempt}).</> : <> <button onClick={() => loadCatalog()}>Retry now</button></>}
    </div>
  );
}

export function ConjunctionList() {
  const cj = useApp((s) => s.conjunctions);
  const now = useApp((s) => s.window.now);
  const active = useApp((s) => s.conjunctionId);
  const [risk, setRisk] = useState<Record<string, boolean>>({ high: true, medium: true, low: false });
  const rows = useMemo(() => cj.filter((c) => risk[c.risk]).sort((a, b) => (a.risk === b.risk ? a.tca.localeCompare(b.tca) : ["high", "medium", "low"].indexOf(a.risk) - ["high", "medium", "low"].indexOf(b.risk))), [cj, risk]);
  const counts = { high: cj.filter((c) => c.risk === "high").length, medium: cj.filter((c) => c.risk === "medium").length, low: cj.filter((c) => c.risk === "low").length };
  return (
    <aside className="panel left" aria-label="Conjunctions">
      <h2>Conjunctions <small>next 24 h · under 5 km</small></h2>
      <div className="chips" role="group" aria-label="Filter by risk">
        {(["high", "medium", "low"] as const).map((r) => (
          <button key={r} className={`chip risk-${r}`} aria-pressed={risk[r]} onClick={() => setRisk({ ...risk, [r]: !risk[r] })}>{riskIcon[r]} {riskText[r]} {counts[r]}</button>
        ))}
      </div>
      <ol className="cj-list">
        {rows.map((c) => (
          <li key={c.id}>
            <button className={`cj-row ${active === c.id ? "active" : ""}`} onClick={() => openConjunction(c.id)} aria-current={active === c.id}>
              <span className={`risk risk-${c.risk}`}>{riskIcon[c.risk]} {riskText[c.risk]}</span>
              <span className="who">{name(c.primaryNorad)} <i>vs</i> {name(c.secondaryNorad)}</span>
              <span className="meta">{relTime(Date.parse(c.tca), now)} · {metres(c.missM)} · Pc {pc(c.pc)}</span>
            </button>
          </li>
        ))}
        {rows.length === 0 ? <li className="empty">No conjunctions match the filter.</li> : null}
      </ol>
    </aside>
  );
}

function orbitOf(o: Obj) {
  const nRev = +o.l2.slice(52, 63), e = +`0.${o.l2.slice(26, 33)}`;
  const a = Math.cbrt(398600.8 / ((nRev * 2 * Math.PI) / 86400) ** 2);
  return { perigee: a * (1 - e) - 6378.135, apogee: a * (1 + e) - 6378.135, incl: +o.l2.slice(8, 16), periodMin: 1440 / nRev };
}

function ObjectCard({ o }: { o: Obj }) {
  const passes = useApp((s) => (s.passes?.norad === o.norad ? s.passes.list : null));
  const all = useApp((s) => s.conjunctions);
  const cj = useMemo(() => all.filter((c) => c.primaryNorad === o.norad || c.secondaryNorad === o.norad), [all, o.norad]);
  const orb = orbitOf(o);
  const op = get().catalog?.operators.find((x) => x.slug === o.operator)?.name;
  return (
    <section aria-label={`Object ${o.name}`}>
      <h2>{o.name}</h2>
      <dl className="kv">
        <dt>Catalog id</dt><dd>{o.norad} <small>(synthetic)</small></dd>
        <dt>Type</dt><dd>{o.type.replace("_", " ")}</dd>
        <dt>Operator</dt><dd>{op ?? "none / unknown"}</dd>
        <dt>Orbit</dt><dd>{n(Math.round(orb.perigee))} × {n(Math.round(orb.apogee))} km, {orb.incl.toFixed(1)}°</dd>
        <dt>Period</dt><dd>{orb.periodMin.toFixed(1)} min</dd>
        <dt>Size / mass</dt><dd>{o.radiusM} m radius · {n(Math.round(o.massKg))} kg</dd>
        <dt>1σ at epoch</dt><dd>{o.sigma.join(" / ")} m (radial / in-track / cross)</dd>
      </dl>
      {cj.length ? <><h3>Conjunctions</h3><ul className="mini">{cj.slice(0, 6).map((c) => <li key={c.id}><button onClick={() => openConjunction(c.id)}>{riskIcon[c.risk]} {name(c.primaryNorad === o.norad ? c.secondaryNorad : c.primaryNorad)} · {metres(c.missM)} · {hhmm(Date.parse(c.tca))}</button></li>)}</ul></> : null}
      <h3>Ground-station passes <small>(next 22 h)</small></h3>
      {passes === null ? <p className="muted">Computing…</p> : passes.length === 0 ? <p className="muted">None above the stations&apos; masks.</p> : (
        <ul className="mini">{passes.slice(0, 8).map((p, k) => <li key={k}>{p.station} · {hhmm(Date.parse(p.aos))}–{hhmm(Date.parse(p.los))} · max {p.maxElevDeg}°</li>)}</ul>
      )}
      <button className="ghost" onClick={() => select(null)}>Back to globe</button>
    </section>
  );
}

export function ConjunctionCard({ c }: { c: Conjunction }) {
  const view = useApp((s) => s.view);
  const plan = useApp((s) => s.plan);
  const now = useApp((s) => s.window.now);
  const a = get().byNorad.get(c.primaryNorad)!, b = get().byNorad.get(c.secondaryNorad)!;
  return (
    <section aria-label="Conjunction">
      <p className={`risk big risk-${c.risk}`}>{riskIcon[c.risk]} {riskText[c.risk]} risk</p>
      <h2>{a.name} <i>vs</i> {b.name}</h2>
      <dl className="kv">
        <dt>Closest approach</dt><dd>{utc(Date.parse(c.tca))} ({relTime(Date.parse(c.tca), now)})</dd>
        <dt>Miss distance</dt><dd>{metres(c.missM)}</dd>
        <dt>Relative speed</dt><dd>{(c.relSpeedMs / 1000).toFixed(2)} km/s</dd>
        <dt>Probability of collision</dt><dd>{pc(c.pc)}</dd>
        <dt>Combined 1σ in the plane</dt><dd>{n(c.sigmaPlaneM[0])} × {n(c.sigmaPlaneM[1])} m</dd>
        <dt>Hard-body radius</dt><dd>{c.hbrM} m</dd>
        <dt>Secondary</dt><dd>{b.type.replace("_", " ")}, 1σ in-track {n(b.sigma[1])} m at epoch</dd>
      </dl>
      <div className="row">
        <button onClick={() => playEncounter()} disabled={get().reduced} title={get().reduced ? "Reduced motion: the closest approach is shown without travel" : undefined}>Play encounter</button>
        {view === "encounter" ? <button className="primary" onClick={() => planAvoidance()}>Plan avoidance</button> : null}
        <button onClick={() => set({ alertOpen: true })}>Create alert rule</button>
      </div>
      {view === "plan" ? <PlanCompare c={c} /> : null}
      <button className="ghost" onClick={() => send({ type: view === "plan" ? "BACK" : "CLEAR" })}>{view === "plan" ? "Back to encounter" : "Close"}</button>
      {plan.status === "error" ? <p role="alert">Planning failed: {plan.error}</p> : null}
    </section>
  );
}

function PlanCompare({ c }: { c: Conjunction }) {
  const plan = useApp((s) => s.plan);
  if (plan.status === "running") return (
    <div className="plan-progress" role="status" aria-live="polite">
      <p>{plan.stage}…</p>
      <progress max={1} value={plan.fraction ?? 0} />
    </div>
  );
  if (plan.status !== "done" || !plan.options) return null;
  if (plan.options.length === 0) return <p>No in-track burn up to 2 m/s, at the allowed lead times, brings Pc below 1 × 10⁻⁶ without creating another approach above it.</p>;
  return (
    <div className="plan">
      <h3>Two avoidance options <small>target Pc ≤ 1 × 10⁻⁶ · {plan.frontier} lead times searched · {n(plan.ms ?? 0)} ms</small></h3>
      <table>
        <thead><tr><th scope="col" /><th scope="col">Option A</th><th scope="col">Option B</th></tr></thead>
        <tbody>
          <tr><th scope="row">Burn</th>{plan.options.map((o, k) => <td key={k}>{hhmm(Date.parse(o.burn))} UTC, {o.leadOrbits} orbits early</td>)}</tr>
          <tr><th scope="row">Δv (in-track)</th>{plan.options.map((o, k) => <td key={k}>{cms(o.dvMs)} {o.dvRicMs[1] < 0 ? "retrograde" : "prograde"}</td>)}</tr>
          <tr><th scope="row">Propellant</th>{plan.options.map((o, k) => <td key={k}>{(o.propellantKg * 1000).toFixed(1)} g</td>)}</tr>
          <tr><th scope="row">New miss</th>{plan.options.map((o, k) => <td key={k}>{metres(o.missKm * 1000)} (was {metres(c.missM)})</td>)}</tr>
          <tr><th scope="row">New Pc</th>{plan.options.map((o, k) => <td key={k}>{pc(o.pc)}</td>)}</tr>
          <tr><th scope="row">New orbit re-screened</th>{plan.options.map((o, k) => <td key={k}>{o.newApproaches.length} approaches under 5 km to the end of the window; worst Pc {o.worst ? `${pc(o.worst.pc)} (${name(o.worst.secondaryNorad)}, ${metres(o.worst.missM)})` : "–"}</td>)}</tr>
        </tbody>
      </table>
      {plan.rejected?.length ? (
        <div className="rejected">
          <h4>Rejected after re-screening</h4>
          <ul className="mini">{plan.rejected.map((o, k) => <li key={k}>▲ {o.leadOrbits} orbits early, {cms(o.dvMs)} {o.dvRicMs[1] < 0 ? "retrograde" : "prograde"}: clears this conjunction but moves {o.worst ? `${name(o.worst.secondaryNorad)} to ${metres(o.worst.missM)} at ${hhmm(Date.parse(o.worst.tca))} UTC (Pc ${pc(o.worst.pc)})` : "another approach above the target"}</li>)}</ul>
        </div>
      ) : null}
      <div className="row" role="radiogroup" aria-label="Choose an option">
        {plan.options.map((_, k) => <button key={k} role="radio" aria-checked={plan.chosen === k} className={plan.chosen === k ? "primary" : ""} onClick={() => set((s) => ({ plan: { ...s.plan, chosen: k as 0 | 1 } }))}>Choose option {"AB"[k]}</button>)}
      </div>
      <p className="muted small">Simulation only: nothing is commanded. Burns are propagated with two-body + J2 and added to the SGP4 path; the secondary is assumed not to maneuver.</p>
    </div>
  );
}

export function Inspector() {
  const view = useApp((s) => s.view);
  const sel = useApp((s) => (s.selected !== null ? s.byNorad.get(s.selected) ?? null : null));
  const c = useApp((s) => s.conjunctions.find((x) => x.id === s.conjunctionId) ?? null);
  if ((view === "encounter" || view === "plan") && c) return <aside className="panel right" aria-label="Inspector"><ConjunctionCard c={c} /></aside>;
  if (view === "focus" && sel) return <aside className="panel right" aria-label="Inspector"><ObjectCard o={sel} /></aside>;
  return (
    <aside className="panel right hint" aria-label="Inspector">
      <h2>Sandbox</h2>
      <p>Click any point on the globe, pick a conjunction on the left, or search with <kbd>⌘K</kbd>. Drag to turn the globe, scroll to zoom; scrub time below.</p>
      <p className="legend"><span className="sw fleet" /> your fleet <span className="sw payload" /> payload <span className="sw rocket_body" /> rocket body <span className="sw debris" /> debris</p>
    </aside>
  );
}

export function Timeline() {
  const w = useApp((s) => s.window);
  const t = useApp((s) => s.simTime);
  const playing = useApp((s) => s.playing);
  const speed = useApp((s) => s.speed);
  const cj = useApp((s) => s.conjunctions);
  const active = useApp((s) => s.conjunctionId);
  if (!w.end) return null;
  const x = (tt: number) => ((tt - w.start) / (w.end - w.start)) * 100;
  const hours = Array.from({ length: 25 }, (_, h) => w.start + h * 3600e3);
  const perHour = hours.slice(0, 24).map((h) => cj.filter((c) => Date.parse(c.tca) >= h && Date.parse(c.tca) < h + 3600e3).length);
  const maxH = Math.max(1, ...perHour);
  return (
    <footer className="timeline" aria-label="Time">
      <div className="transport">
        <button onClick={() => set({ playing: !playing, motionPaused: false })} aria-keyshortcuts="Space">{playing ? "Pause" : "Play"}</button>
        <label>Speed <select value={speed} onChange={(e) => set({ speed: +e.target.value })}>{[1, 10, 60, 300, 600].map((v) => <option key={v} value={v}>{v}×</option>)}</select></label>
        <button onClick={() => jump(w.now)}>Now</button>
        <output className="clock" aria-live="off">{utc(t)}</output>
      </div>
      <div className="track">
        <svg viewBox="0 0 100 30" preserveAspectRatio="none" aria-hidden>
          {perHour.map((v, h) => <rect key={h} x={(h / 24) * 100 + 0.3} width={100 / 24 - 0.6} y={30 - (v / maxH) * 10} height={(v / maxH) * 10} className="hist" />)}
          {cj.filter((c) => c.risk !== "low").map((c) => (
            <line key={c.id} x1={x(Date.parse(c.tca))} x2={x(Date.parse(c.tca))} y1={c.risk === "high" ? 2 : 8} y2={19} className={`tick risk-${c.risk} ${active === c.id ? "active" : ""}`} />
          ))}
          <line x1={x(w.now)} x2={x(w.now)} y1={0} y2={30} className="now" />
          <line x1={x(t)} x2={x(t)} y1={0} y2={30} className="cursor" />
        </svg>
        <input type="range" min={w.start} max={w.end} step={10000} value={t} aria-label="Simulation time" aria-valuetext={utc(t)}
          onChange={(e) => { set({ playing: false }); jump(+e.target.value); }} />
        <div className="hours" aria-hidden>{hours.filter((_, h) => h % 3 === 0).map((h) => <span key={h} style={{ left: `${x(h)}%` }}>{hhmm(h)}</span>)}</div>
      </div>
      <p className="tl-legend">Bars: close approaches per hour (all risks). Marks: ▲ high and ◆ medium conjunctions. Line: now.</p>
    </footer>
  );
}

export function Notices() {
  const notices = useApp((s) => s.notices);
  const rules = useApp((s) => s.rules);
  if (!notices.length && !rules.length) return null;
  return (
    <div className="notices" role="log" aria-label="Notifications">
      {notices.slice(0, 3).map((x) => (
        <div key={x.id} className="notice"><b>{x.delivered === "simulated" ? "Simulated e-mail" : x.delivered === "smtp-sink" ? "E-mail sent to the local mail sink" : "Notification queued"}</b><span>{x.text}</span></div>
      ))}
      {rules.length ? <p className="muted small">{rules.length} alert rule{rules.length > 1 ? "s" : ""} active.</p> : null}
    </div>
  );
}

export function EncounterReadout() {
  const c = useApp((s) => s.conjunctions.find((x) => x.id === s.conjunctionId) ?? null);
  const reduced = useApp((s) => s.reduced);
  if (!c) return null;
  return (
    <div className="enc-legend">
      <p><b>Encounter frame</b> · centred on {name(c.primaryNorad)} · grid 200 m · playback {reduced ? "off (reduced motion)" : "0.2× real time"}</p>
      <ul>
        <li><span className="sw fleet" /> primary (marker enlarged; hard-body circle {c.hbrM} m is drawn true size)</li>
        <li><span className="sw sec" /> {name(c.secondaryNorad)} and its straight relative path ({(c.relSpeedMs / 1000).toFixed(2)} km/s)</li>
        <li><span className="sw cov" /> combined uncertainty: 1σ and 3σ in the encounter plane, 1σ ellipsoid in 3D</li>
        <li><span className="sw optA" /> <span className="sw optB" /> secondary&apos;s pass after option A / B (plan view)</li>
      </ul>
      <EncounterPhase />
    </div>
  );
}

function EncounterPhase() {
  const [, force] = useState(0);
  useEffect(() => { const iv = setInterval(() => force((k) => k + 1), 250); return () => clearInterval(iv); }, []);
  const c = get().conjunctions.find((x) => x.id === get().conjunctionId);
  if (!c) return null;
  const range = Math.hypot(c.missM, encounterClock.t * c.relSpeedMs);
  if (get().reduced) return <p className="phase">Closest approach: {metres(c.missM)} (shown without travel)</p>;
  return <p className="phase" aria-live="polite">{encounterClock.phase === "idle" ? "Press Play encounter to watch the pass." : encounterClock.phase === "closest" ? `Closest approach: ${metres(c.missM)}` : `Range ${metres(range)}`}</p>;
}
